{% set name = "pytest-randomly" %}
{% set version = "3.15.0" %}
{% set name_url = name.split('-')[0]+"_"+name.split('-')[1] %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name_url }}/{{ name_url }}-{{ version }}.tar.gz
  sha256: b908529648667ba5e54723088edd6f82252f540cc340d748d1fa985539687047

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - wheel
  run:
    - python
    - importlib-metadata >=3.6.0 # [py<310]
    - pytest 

test:
  imports:
    - pytest_randomly
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-randomly
  summary: Pytest plugin to randomly order tests and control random.seed
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: |
   Pytest plugin to randomly order tests and control random.seed. By resetting the random seed to a repeatable number
   for each test, tests can create data based on random numbers and yet remain repeatable, for example factory boy's
   fuzzy values. This is good for ensuring that tests specify the data they need and that the tested system is not
   affected by any data that is filled in randomly due to not being specified. Pytest will automatically find the
   plugin and use it when you run pytest.
  doc_url: https://github.com/pytest-dev/pytest-randomly
  dev_url: https://github.com/pytest-dev/pytest-randomly

extra:
  recipe-maintainers:
    - cpcloud
