{% set name = "pytest-randomly" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pytest-dev/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  # url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: dc0ad4fc1ff37344b37026063b9587596052215c670094439d68e0eab72cd684

build:
  skip: true  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=77
  run:
    - python
    - importlib-metadata >=3.6  # [py<310]
    - pytest

# >           raise ValueError("Pytest terminal summary report not found")
{% set deselect_tests = " --deselect=tests/test_pytest_randomly.py::test_xdist" %}
# E   ModuleNotFoundError: No module named 'model_bakery'
{% set deselect_tests = deselect_tests + " --deselect=tests/test_pytest_randomly.py::test_model_bakery" %}
# E       AssertionError: assert {'errors': 1,...pped': 0, ...} == {'errors': 0,...pped': 0, ...}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_pytest_randomly.py::test_entrypoint_injection" %}
# Missing factory_boy for py314
{% set deselect_tests = deselect_tests + " --deselect=tests/test_pytest_randomly.py::test_factory_boy" %}  # [py==314]

test:
  source_files:
    - tests
  imports:
    - pytest_randomly
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v {{ deselect_tests }} tests
  requires:
    - pip
    - numpy
    - faker
    - factory_boy  # [py<314]

about:
  home: https://github.com/pytest-dev/pytest-randomly
  summary: Pytest plugin to randomly order tests and control random.seed
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: |
    Pytest plugin to randomly order tests and control random.seed. By resetting the random seed to a repeatable number
    for each test, tests can create data based on random numbers and yet remain repeatable, for example factory boy's
    fuzzy values. This is good for ensuring that tests specify the data they need and that the tested system is not
    affected by any data that is filled in randomly due to not being specified. Pytest will automatically find the
    plugin and use it when you run pytest.
  doc_url: https://github.com/pytest-dev/pytest-randomly
  dev_url: https://github.com/pytest-dev/pytest-randomly

extra:
  recipe-maintainers:
    - cpcloud
