{% set name = "pytest-randomly" %}
{% set version = "3.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 11bf4d23a26484de7860d82f726c0629837cf4064b79157bd18ec9d41d7feb26

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - importlib-metadata >=3.6.0  # [py<310]
    - pytest

test:
  imports:
    - pytest_randomly
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-randomly
  summary: Pytest plugin to randomly order tests and control random.seed
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: |
    Pytest plugin to randomly order tests and control random.seed. By resetting the random seed to a repeatable number
    for each test, tests can create data based on random numbers and yet remain repeatable, for example factory boy's
    fuzzy values. This is good for ensuring that tests specify the data they need and that the tested system is not
    affected by any data that is filled in randomly due to not being specified. Pytest will automatically find the
    plugin and use it when you run pytest.
  doc_url: https://github.com/pytest-dev/pytest-randomly
  dev_url: https://github.com/pytest-dev/pytest-randomly

extra:
  recipe-maintainers:
    - cpcloud